# Written asignment

__Why did the virtual class hosted by Metro Nashville Public Schools became so
successful ?__

The virtual class hosted by Metro Nashville Public Schools became so successful
because parents can actually participate to oral speaking courses.
Parents who didn't have the chance to learn english before can now study it
through virtual english courses.
It also set an example for their children to learn more.
Those courses also helps them for their every day life such as for shopping,
socializing, etc.
In my point of view, I think it became so successful because it is open for
everyone and it is simple to use.
People who don't have time to participate to physical classes can now attend
these classes at home with only a phone. It is also more accessible for people
who have difficulties to talk to people, in particular, immigrant.

__Do you believe online learning is the future of education ?__

This report shows us that online learning may possibly be the future of
education. Virtual classes helps people who don't necessarily have time to go to
school physically.
Personnally, I think online learning can be useful in addition of physical
classes.
It is important for student to keep contact with their classmate and keep
socializing.
Too much online classes can really be boring and some students can lose track of
the courses, because there are too much distracted or they are not enough
supervised by their teacher.
That is why online learning might not be the future of education.
It can give students more time at home to relax, study or do physical activities
but it cannot replace physical classes.
