---
title: "Java avancé TP4: les Threads et la concurrence"
subtitle: "M1 Informatique, groupe apprenti"
author: "Mathieu Chan"
date: "2021-10-24"
geometry: margin=2cm
header-includes: |
	\usepackage{titling}
	\usepackage{fancyhdr}
	\usepackage{graphicx}

	\pagestyle{fancy}
	\fancyhead[LO,LE]{compte rendu de java}
	\fancyfoot[L]{\thedate}
footer-left: "2021-2022"
output:
    pdf_document:
        number_sections: true
		font-size: 10
---

\pagebreak

# Exercice 1

## 1.1

__Rappeler ce que cela veut dire qu'une classe n'est pas thread safe__

Une classe qui n'est pas thread-safe est une classe qui ne permet pas d'éviter
que les threads provoquent des états un incohérent

## 1.2

__Expliquer pourquoi la classe HonorBoard n'est pas thread safe__

Elle n'est pas thread-safe car il est possible de créer des combinaisons de nom
et prénom incohérent. par exemple __John Odd__ et __Jane Doe__.

`java -cp bin fr.umlv.conc.HonorBoard | grep "John Odd"`

## 1.4

__peut-on remplacer la ligne:__

`System.out.println(board);`

__par la ligne:__

`System.out.println(board.getFirstName() + ' ' + board.getLastName());`

__avec les deux getters définis comme d'habitude ?__

Non, il faudrait rendre ces méthodes thread-safe aussi.

# Exercice 2

## 2.1

__Rappeler ce que ré-entrant veut dire__

c'est système de verrou pour les threads

# Exercice 3

## 3.1

__Pourquoi n'est il pas possible d’arrêter une thread de façon non coopérative ?__

C'est une caractéristique d'une thread, le seul à pouvoir l'arrêter est
lui-même. (lorsque le code est fini)

## 3.2

__Qu'est-ce qu'une opération bloquante ?__

Une opération bloquante est une opération qui empêche une thread d'accéder à une
ressource.

__À quoi sert la méthode d'instance interrupt() de la classe Thread ?__

__interrupt()__ permet de demander à une thread de s'interrompre.
C'est principalement une convention.

__Expliquer comment interrompre une thread en train d'effectuer une opération
bloquante__

Il faut faire en sorte que la thread possède un code qui _return_ et capture
l'interruption

## 3.4

__Et si vous pouvez modifier le code de slow (mais pas sa signature), que
pouvez-vous faire ?__

On ne peut rien faire car on ne peut pas prolonger l'interruption.
La seule chose que l'on peut faire c'est arrêter la boucle _for_ plus rapidement

## 3.5

__Comment faire pour interrompre la thread à coup sûre, si elle effectue à la
fois des opérations bloquantes et non bloquantes ?__

On utilise __interrupt()__ et __Thread.interrupted__

## 3.6

__Et si vous pouvez modifier le code de slow ET sa signature, que faites-vous ?__

## 3.7

__Expliquer la (trop) subtile différence entre les méthodes Thread.interrupted
et thread.isInterrupted de la classe Thread__

__Thread.interrupted__ vérifie qu'une intéruption a bien été appelé et efface
les évènements d'intéruption.

__Pourquoi dit-on que la méthode Thread.interrupted est mal nommée ?__

La méthode devrait s'appeler de __interruptedAndClear__

## 3.9

__Comment faire pour que le programme se termine si l'on fait un Ctrl-D dans le terminal ?__

Il suffit de créer des threads daemon à la place de thread classique

# Conclusion

Lors de ce TP, j'en ai appris plus sur les __Thread__ notamment sur leur
fonctionnement.
J'ai aussi compris l'utilité d'une classe _thread-safe_ et le fonctionnement
d'une demande d'interruption.
Les difficultés de ce TP sont principalement de comprendre ce que l'on peut
faire avec un thread mais aussi de savoir les actions adéquates que l'on peut
exécuter sur elles. Notamment avec les interruptions.
Je vais continuer à revoir le fonctionnement des threads et des verrous pour
être plus efficace lors que je travaillerai dessus.
